# /az-csec-app-ci-cd.yml
#
# -----------------------------------------------------------------------------
# Pipeline: csec-API-Service CI/CD
#
# Description: Automates the build and deployment of the csec-API-Service
#              Flask application. It builds a Docker image, pushes it to the
#              GitHub Container Registry (GHCR), and deploys it to various
#              Azure App Service environments.
#
# Stages:
# 1. Build: Lints the source code, builds a Docker image, and pushes it to GHCR.
# 2. Deploy_Dev: Deploys the container image to the Development App Service.
# 3. Deploy_Test: Deploys the container image to the Test App Service.
#
# Trigger Configuration:
# This pipeline is configured for manual execution. For continuous integration,
# a branch trigger with path filters for 'csec-api-app/' should be implemented.
# -----------------------------------------------------------------------------

trigger: none
pr: none

# Use the self-hosted agent pool
pool:
  name: "csec-az-devops-agent-pool"

# Defines pipeline-level variables for configuration and parameterization.
# A structured naming convention (e.g., app.image.name) is used for clarity.
variables:
  # Links to the 'csec-terraform-secrets' variable group to securely access
  # secrets like registry credentials.
  - group: csec-terraform-secrets

  # General Configuration
  - name: config.azureServiceConnection
    value: "csec-az-devops-main"
  - name: config.githubRegistryServiceConnection
    value: "csec-az-github-registry"
  - name: config.buildContainerImage
    value: "ghcr.io/hrithviks/csec-build-container:latest"

  # Application Configuration
  - name: app.sourceDirectory
    value: "$(System.DefaultWorkingDirectory)/csec-api-app"
  - name: app.image.name
    value: "ghcr.io/hrithviks/csec-api-service"
  - name: app.image.tag
    value: "$(Build.BuildId)"

  # Dev Environment Configuration
  - name: dev.appName
    value: "csec-app-service-dev"
  - name: dev.resourceGroup
    value: "csec-app-rg-dev"

  # Test Environment Configuration
  - name: test.appName
    value: "csec-app-service-test"
  - name: test.resourceGroup
    value: "csec-app-rg-test"

# Define container resources used by the pipeline.
# The jobs will run inside this container, which has Terraform pre-installed.
# The jobs will run inside this container, which is pre-configured with all
# necessary build tools (e.g., Flake8, Docker CLI).
resources:
  containers:
    - container: csec-build-container
      image: $(config.buildContainerImage)
      endpoint: "csec-github-registry"

stages:
  ####################
  # CI - Build Stage #
  ####################
  - stage: Build
    displayName: "Build and Push Docker Image"
    jobs:
      - job: BuildImage
        displayName: "Build, Tag, and Push to GHCR"
        container: csec-build-container
        steps:
          - checkout: self

          # Step 1: Performs static code analysis using Flake8 to enforce
          # code quality and style consistency.
          - script: |
              flake8 .
            displayName: "Run Code Linting"
            workingDirectory: $(app.sourceDirectory)

          # Step 1: Log in to GitHub Container Registry
          - task: Docker@2
            displayName: "Login to GHCR"
            inputs:
              command: "login"
              containerRegistry: $(config.githubRegistryServiceConnection)

          # Step 3: Builds the Docker image from the application source code and
          # pushes it to GHCR with two tags: the unique Build ID and 'latest'.
          - task: Docker@2
            displayName: "Build and Push Image"
            inputs:
              command: "buildAndPush"
              repository: $(app.image.name)
              dockerfile: "$(app.sourceDirectory)/Dockerfile"
              buildContext: "$(app.sourceDirectory)"
              tags: |
                $(app.image.tag)
                latest

          # Step 4: Logs out from the container registry. This is a critical
          # security practice to ensure credentials do not persist on the agent.
          - task: Docker@2
            displayName: "Logout from GHCR"
            condition: always() # Ensures this step runs even if previous steps fail
            inputs:
              command: "logout"
              containerRegistry: $(config.githubRegistryServiceConnection)

  ######################
  # CD - Deploy Stages #
  ######################

  # Development Deployment Stage
  - stage: Deploy_Dev
    displayName: "Deploy to Dev"
    dependsOn: Build
    jobs:
      - deployment: Deploy_App_Dev
        displayName: "Deploy App to Dev Environment"
        container: csec-build-container
        environment: "csec-dev" # This targets an Azure DevOps Environment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - template: templates/app-deploy.yml
                  parameters:
                    azureServiceConnection: $(config.azureServiceConnection)
                    appName: $(dev.appName)
                    resourceGroupName: $(dev.resourceGroup)
                    imageName: "$(app.image.name)"
                    imageTag: "$(app.image.tag)"

  # Test Deployment Stage
  - stage: Deploy_Test
    displayName: "Deploy to Test"
    condition: false # Disable this stage for now
    dependsOn: Deploy_Dev # Set dependency on DEV stage
    jobs:
      - deployment: Deploy_App_Test
        displayName: "Deploy App to Test Environment"
        container: csec-build-container
        environment: "csec-test" # This targets an Azure DevOps Environment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - template: templates/app-deploy.yml
                  parameters:
                    azureServiceConnection: $(config.azureServiceConnection)
                    appName: "$(test.appName)"
                    resourceGroupName: "$(test.resourceGroup)"
                    imageName: "$(app.image.name)"
                    imageTag: "$(app.image.tag)"
