# /az-csec-app-ci-cd.yml
#
# Description:
# This pipeline automates the CI/CD process for the CSB-API-Service Flask application.
# It orchestrates the build and deployment across multiple environments (Dev, Test)
# by leveraging a reusable template for deployment steps.
#
# Stages:
# 1. Build: Compiles the application into a Docker container, tags it, and
#    pushes it to the GitHub Container Registry (GHCR).
# 2. Deploy_Dev: Deploys the container image to the Development App Service.
# 3. Deploy_Test: Deploys the container image to the Test App Service.
#
# Triggers:
# The pipeline is currently set to manual trigger. For CI, this should be
# configured to trigger on commits to the 'main' branch with path filters
# for 'csb-api-app/'.

# For now, set to manual trigger.
trigger: none
pr: none

# Use the self-hosted agent pool
pool:
  name: "csb-az-devops-agent-pool"

# Pipeline-level variables
variables:
  # Link the variable group for secrets and common variables.
  - group: csb-terraform-secrets
  # Define individual variables as list items
  - name: azureServiceConnection
    value: "csb-az-devops-main"
  - name: githubRegistryServiceConnection
    value: "csb-github-registry"
  - name: appWorkingDirectory
    value: "$(System.DefaultWorkingDirectory)/csb-api-app"
  - name: imageName
    value: "ghcr.io/hrithviks/csb-api-service"
  - name: imageTag
    value: "$(Build.BuildId)"

#######################
# CI - Build Stage    #
#######################
stages:
  - stage: Build
    displayName: "Build and Push Docker Image"
    jobs:
      - job: BuildImage
        displayName: "Build, Tag, and Push to GHCR"
        steps:
          - checkout: self

          # Step 1: Run Linting
          # This step installs flake8 and checks the application code for style
          # and syntax issues. This helps maintain code quality.
          - script: |
              python -m pip install --upgrade pip
              pip install flake8
              flake8 $(appWorkingDirectory)
            displayName: "Run Code Linting"
            workingDirectory: $(appWorkingDirectory)

          # Step 1: Log in to GitHub Container Registry
          - task: Docker@2
            displayName: "Login to GHCR"
            inputs:
              command: "login"
              containerRegistry: $(githubRegistryServiceConnection)

          # Step 2: Build and push the Docker image
          # The image is tagged with both the Build ID and 'latest'
          - task: Docker@2
            displayName: "Build and Push Image"
            inputs:
              command: "buildAndPush"
              repository: $(imageName)
              dockerfile: "$(appWorkingDirectory)/Dockerfile"
              buildContext: "$(appWorkingDirectory)"
              tags: |
                $(imageTag)
                latest

  #######################
  # CD - Deploy Stages  #
  #######################

  # Development Deployment Stage
  - stage: Deploy_Dev
    displayName: "Deploy to Dev"
    dependsOn: Build
    jobs:
      - deployment: Deploy_App_Dev
        displayName: "Deploy App to Dev Environment"
        environment: "csb-dev" # This targets an Azure DevOps Environment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - template: templates/app-deploy.yml
                  parameters:
                    azureServiceConnection: $(azureServiceConnection)
                    appName: "csb-api-app-service-dev"
                    imageName: "$(imageName)"
                    imageTag: "$(imageTag)"

  # Test Deployment Stage
  - stage: Deploy_Test
    displayName: "Deploy to Test"
    dependsOn: Deploy_Dev # Set dependency on DEV stage
    jobs:
      - deployment: Deploy_App_Test
        displayName: "Deploy App to Test Environment"
        environment: "csb-test" # This targets an Azure DevOps Environment
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: none
                - template: templates/app-deploy.yml
                  parameters:
                    azureServiceConnection: $(azureServiceConnection)
                    appName: "csb-api-app-service-test"
                    imageName: "$(imageName)"
                    imageTag: "$(imageTag)"
